# ============================================================================== #
# MCMC FITTING SCRIPT
# Runs the model on the data generated by the simulation script
# ============================================================================== #
# NOTE: this script is designed to run on a virtual computer

library(cmdstanr)
library(posterior)
library(loo)
library(bayesplot)
library(ggplot2)
library(splines)
library(Matrix)
library(data.table)

# ============================================================================== #
# 0. LIBRARIES ####
# ============================================================================== #

set.seed(42)

# --- 0. DOWNLOAD FILES (OneDrive) ---
library(Microsoft365R)
od <- get_personal_onedrive(auth_type = "device_code")
od$download_file("Model.stan", dest="Model.stan", overwrite=TRUE)
od$download_file("stan_data_production.rds", dest="stan_data_production.rds", overwrite=TRUE)

# ============================================================================== #
# COMPILATION ####
# ============================================================================== #
mod <- cmdstan_model("Model.stan")

set.seed(42)

# 1. LOAD GENERATED DATA & MODEL
stan_data <- readRDS("stan_data_production.rds")

# 2. INITIALIZATION 
# Initial values are within the bounds of the Stan priors
S <- stan_data$S
T_total <- stan_data$T_total
N_spatial_bf <- stan_data$N_spatial_bf

make_init <- function() {
  list(
    r = runif(1, 0.05, 0.2),
    log_alpha = rnorm(1, 2.7, 0.5),
    N0_proportion = runif(1, 0.2, 0.4),
    
    # Temporal
    sigma_year = runif(1, 0.01, 0.05),
    eps_year_raw = rnorm(T_total, 0, 0.01),
    
    # Spatial Fields
    rho_phi = runif(1, 50, 150),
    rho_gamma = runif(1, 100, 200),
    sigma_phi = runif(1, 0.1, 0.2),
    phi_eta = rnorm(N_spatial_bf, 0, 0.01),
    sigma_gamma = runif(1, 0.05, 0.1),
    gamma_eta = rnorm(N_spatial_bf, 0, 0.01),
    
    # Detection & Thermal
    logit_p = rnorm(1, -2.0, 0.2),
    thermal_max = rnorm(1, 0, 1),
    T_nodes = c(2.0, 11.0),
    slope_L = runif(1, 1.0, 1.5),
    slope_R = runif(1, 1.0, 1.5)
  )
}

# 3. FIT 
fit_param_ST <- mod$sample(
  data = stan_data,
  chains = 6, 
  parallel_chains = 6,    
  iter_warmup = 150,
  iter_sampling = 150,
  init = make_init, 
  adapt_delta = 0.9,
  max_treedepth = 12,    
  refresh = 50
)

# 4. SAVE AND UPLOAD
fit_param_ST$save_object("fit_generative_validation.rds")
od <- get_personal_onedrive(auth_type = "device_code")
od$upload_file("fit_generative_validation.rds", dest = "Thesis_Data/fit_generative_validation.rds")

